language: node_js
node_js:
  - '8'
before_install:
  - npm add -D vuepress
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN 
  keep-history: false
  on:
    branch: master